version: '3'


services:
  # Server container
  nginx:
    build:
      context: docker/dev/nginx
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www
      - ./docker/dev/nginx/logs:/var/log/nginx
    ports:
      # Laravel port
      - 8081:81
    links:
      - laravel

  # PHP FastCGI Process Manager container
  laravel:
    build:
      context: docker/dev/laravel
      dockerfile: Dockerfile
    volumes:
      - ./laravel:/var/www/laravel
    environment:
      # If you down want to use xDebug, set remote_enable=0
      XDEBUG_CONFIG: "remote_host=172.17.0.1 remote_enable=1"
      PHP_IDE_CONFIG: "serverName=Docker"
    links:
      - mysql

  # MySQL database container
  mysql:
    build:
      context: docker/dev/mysql
      dockerfile: Dockerfile
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      # Database volume
      - database:/var/lib/mysql
    ports:
      - 33061:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123456

volumes:
  database:
    driver: local
